# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='socialtoken',
            name='app',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='socialaccount.SocialApp'),
        ),
    ]
