# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    db_alias = schema_editor.connection.alias

    SocialAccount = apps.get_model("socialaccount", "SocialAccount")
    SocialApp = apps.get_model("socialaccount", "SocialApp")

    from ..models import SocialProvider

    SocialProvider.load()
    for ModelClass in [SocialApp, SocialAccount]:
        for object in ModelClass.objects.all():
            print("Doing ", object.id)
            object.provider_instance_id = SocialProvider.get_by_name(object.provider).get_db_instance().id
            object.save(update_fields=["provider_instance"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_auto_20170728_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='provider_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialaccount.SocialProvider'),
        ),
        migrations.AddField(
            model_name='socialapp',
            name='provider_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='socialaccount.SocialProvider'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
