# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20170728_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='provider_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='socialaccount.SocialProvider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialapp',
            name='provider_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='socialaccount.SocialProvider'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together=set([('provider_instance', 'uid')]),
        ),
    ]
