# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0005_auto_20170728_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='socialapp',
            name='provider',
        ),
    ]
