# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'Jurisdiction',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('local_name', models.CharField(max_length=64, unique=True)),
                ('iso_code', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='TranslationEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4096)),
            ],
            options={
                'db_table': 'TranslationEntry',
            },
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=4096, unique='True')),
                ('comment', models.CharField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'db_table': 'TranslationKey',
            },
        ),
        migrations.AddField(
            model_name='translationentry',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localization.TranslationKey'),
        ),
        migrations.AddField(
            model_name='translationentry',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='localization.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='translationentry',
            unique_together=set([('key', 'language')]),
        ),
    ]
