# Generated by Django 4.2.5 on 2023-11-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0002_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='local_name',
            field=models.CharField(max_length=64),
        ),
    ]
