# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=True, verbose_name='Should be seen by non-admins')),
                ('message', models.CharField(blank=True, max_length=2048, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='HTTP Status code')),
                ('app', models.CharField(blank=True, max_length=64, null=True, verbose_name='Django app')),
                ('translation_key', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.TranslationKey')),
            ],
            options={
                'db_table': 'ErrorMessage',
            },
            bases=(models.Model, Exception),
        ),
        migrations.AlterUniqueTogether(
            name='errormessage',
            unique_together=set([('message', 'app')]),
        ),
    ]
