# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('errors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errormessage',
            name='translation_key',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.TranslationKey'),
        ),
    ]
