# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_forums', to='forum.Forum')),
            ],
            options={
                'db_table': 'Forum',
            },
        ),
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('num_views', models.IntegerField(default=0)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('hidden', models.BooleanField(default=False)),
                ('pinned_index', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='chat.MessageInstance')),
                ('message_thread', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='forum_thread', to='chat.MessageThread')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='forum.Forum')),
            ],
            options={
                'db_table': 'ForumThread',
            },
        ),
        migrations.AlterUniqueTogether(
            name='forumthread',
            unique_together=set([('title', 'parent')]),
        ),
        migrations.AlterUniqueTogether(
            name='forum',
            unique_together=set([('name', 'parent')]),
        ),
    ]
