# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('max_message_size', models.IntegerField(default=4096)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserGroup')),
            ],
            options={
                'db_table': 'GroupChat',
            },
        ),
        migrations.CreateModel(
            name='MessageInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=16384)),
                ('hidden', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
            options={
                'db_table': 'MessageInstance',
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_name', models.CharField(max_length=256)),
                ('messages_editable', models.BooleanField(default=False)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('muted', models.BooleanField(default=False)),
                ('markup_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'MessageThread',
            },
        ),
        migrations.CreateModel(
            name='PrivateChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_unread_message', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('message_thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.MessageThread')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrivateChat',
            },
        ),
        migrations.AddField(
            model_name='messageinstance',
            name='message_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.MessageThread'),
        ),
        migrations.AddField(
            model_name='messageinstance',
            name='reaction_collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.UserReactionCollection'),
        ),
        migrations.AddField(
            model_name='messageinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='message_thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.MessageThread'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together=set([('user1', 'user2')]),
        ),
    ]
