# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 00:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    MessageThread = apps.get_model("chat", "MessageThread")
    db_alias = schema_editor.connection.alias
    for message_thread in MessageThread.objects.using(db_alias).all():
        last_message = message_thread.messages.order_by("-id").first()
        if last_message:
            message_thread.last_activity = last_message.time_added
            message_thread.save(update_fields=["last_activity"])


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_groupchat_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
