# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.RemoveField(
            model_name='emailstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailStatus',
        ),
    ]
