# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170529_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_user', to='accounts.UnverifiedEmail')),
            ],
            options={
                'db_table': 'TempUser',
            },
        ),
    ]
