# Generated by Django 3.2.8 on 2021-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tempuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempuser',
            name='extra',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='usercustomsettings',
            name='settings',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='data',
            field=models.JSONField(),
        ),
    ]
