# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import establishment.emailing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('system_use', models.BooleanField(default=False)),
                ('from_address', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'EmailCampaign',
            },
        ),
        migrations.CreateModel(
            name='EmailGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('host', models.CharField(max_length=256)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'EmailGateway',
            },
        ),
        migrations.CreateModel(
            name='EmailStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=establishment.emailing.models.random_key, max_length=64, null=True, unique=True)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
                ('time_first_read', models.DateTimeField(blank=True, null=True)),
                ('time_last_read', models.DateTimeField(blank=True, null=True)),
                ('read_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emailing.EmailCampaign')),
            ],
            options={
                'db_table': 'EmailStatus',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('html', models.TextField(max_length=131072)),
                ('version', models.IntegerField(default=1)),
                ('plaintext', models.TextField(max_length=131072)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='emailing.EmailCampaign')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emailing.EmailGateway')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localization.Language')),
            ],
            options={
                'db_table': 'EmailTemplate',
            },
        ),
        migrations.AddField(
            model_name='emailstatus',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emailing.EmailTemplate'),
        ),
        migrations.AddField(
            model_name='emailstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emailing.EmailGateway'),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together=set([('campaign', 'version', 'language')]),
        ),
        migrations.AlterUniqueTogether(
            name='emailstatus',
            unique_together=set([('user', 'campaign')]),
        ),
    ]
