# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0003_auto_20170511_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emailing.EmailGateway'),
        ),
        migrations.AlterField(
            model_name='emailstatus',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='emailing.EmailCampaign'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='emailing.EmailGateway'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='localization.Language'),
        ),
    ]
