# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailing', '0004_auto_20170729_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='manual_send_only',
            field=models.BooleanField(default=False),
        ),
    ]
