# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import establishment.emailing.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailing', '0005_emailcampaign_manual_send_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('email_unsubscribe_key', models.CharField(default=establishment.emailing.models.random_key, max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('subscription_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'EmailNewsletterSubscription',
            },
        ),
        migrations.AlterField(
            model_name='emailstatus',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emailstatus',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='emailing.EmailNewsletterSubscription'),
        ),
        migrations.AlterUniqueTogether(
            name='emailstatus',
            unique_together=set([('user', 'subscription', 'campaign')]),
        ),
    ]
