# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 09:46
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseconfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('prompt_for_confirmation', models.BooleanField(default=False)),
                ('class_instance', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'CommandInstance',
            },
        ),
        migrations.CreateModel(
            name='CommandRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_finished', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Successful'), (3, 'Failed')], default=0)),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('log_entries', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('command_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baseconfig.CommandInstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CommandRun',
            },
        ),
    ]
