# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0002_commandinstance_commandrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandinstance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='commandinstance',
            name='prompt_for_confirmation',
        ),
        migrations.AlterField(
            model_name='commandrun',
            name='status',
            field=models.IntegerField(choices=[(0, 'Waiting'), (1, 'Running'), (2, 'Failed'), (3, 'Successful')], default=0),
        ),
    ]
