# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0003_auto_20170614_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateglobalsettings',
            name='export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privateglobalsettings',
            name='export_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publicglobalsettings',
            name='export',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publicglobalsettings',
            name='export_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
