# Generated by Django 3.2.8 on 2021-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0005_commandrun_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandrun',
            name='arguments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandrun',
            name='log_entries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commandrun',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privateglobalsettings',
            name='value',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='publicglobalsettings',
            name='value',
            field=models.JSONField(),
        ),
    ]
