# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public', models.BooleanField(default=False, verbose_name='Should be accessible by ID by everyone')),
                ('version', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('dependency', models.CharField(blank=True, default='', max_length=512, verbose_name='The javascript to import before rendering this article')),
                ('markup', models.TextField(default='', max_length=262144)),
                ('compiled_json', models.TextField(blank=True, default='{}', max_length=262144)),
                ('compiled_html', models.TextField(blank=True, default='', max_length=524288)),
                ('author_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('base_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Article')),
                ('language', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localization.Language')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('markup', models.TextField(default='')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ArticleEdit',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='content.Tag')),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='TermDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256, unique=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('definition', models.TextField(max_length=8192)),
            ],
            options={
                'db_table': 'TermDefinition',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=32768)),
                ('client_message', models.TextField(default='{}', max_length=65536)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserFeedback',
            },
        ),
        migrations.AlterUniqueTogether(
            name='articleedit',
            unique_together=set([('article', 'version')]),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('base_article', 'language')]),
        ),
    ]
