# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170912_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairequestion',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority inside questionnaire'),
        ),
        migrations.AddField(
            model_name='questionnairequestionoption',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Priority inside question'),
        ),
    ]
