# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20170913_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionnairequestionresponse',
            unique_together=set([('instance', 'question')]),
        ),
    ]
